//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDDModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class MensajeriaPriv
    {
        public int IDMensPriv { get; set; }
        public Nullable<int> IDUsuarioE { get; set; }
        public Nullable<int> IDUsuarioR { get; set; }
        public string Mensaje { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.TimeSpan> Hora { get; set; }
        public Nullable<bool> Leido { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}
